### ISSUE TITLE
pip installable tools

### ISSUE THREAD

**Issue by tjfulle** [psakievich/snl-spack-tools#3]
Feature request: make tools pip installable.  Spack has the ability to read extensions from entry points, removing the need to point spack to your extensions.  Simply:

```console
$ python3 -m venv venv
$ source activate venv/bin/activate
$ python3 -m pip install <the name of this package>
$ spack -h
```

voila, spack now sees your extensions!

To make this happen:

- [ ] The spack tools must be a python package that can be installed via pip
- [ ] Add the proper entry points logic to `pyproject.toml`

The entry point spec in `pyproject.toml` will look like:

```toml
[project.entry-points."spack.config"]
"my-name" = "some-python-function"
```

where `some-python-function` is a function called that returns a path to this package's configuration scope.  You can also add an entry point to extensions.  In my projects, I just point to the configuration scope and in there add the paths to extension paths.  Eg,

```yaml
config:
  extensions:
  - ...
```

see the [Spack documentation](https://spack.readthedocs.io/en/latest/extensions.html#registering-extensions-via-entry-points) on more details for setting up entry points.
